### PR TITLE
Make MarkerGroup props optional (fixes #66)

### LINKED ISSUE #66: Incorrect types in index.d.ts
I have a static map component in typescript that I'm trying to render but it is complaining that size, color, iconUrl, label and anchor for the marker component are missing even though in the README.md it is specified as optional. Simple changing these props to be optional like this

```
interface MarkerGroup {
    size?: 'tiny' | 'mid' | 'small' | 'normal';
    color?:
      | 'black'
      | 'brown'
      | 'green'
      | 'purple'
      | 'yellow'
      | 'blue'
      | 'gray'
      | 'orange'
      | 'red'
      | 'white'
      | number;
    iconURL?: string;
    label?: string;
    scale?: '1' | '2' | '4' | 1 | 2 | 4;
    anchor?:
      | 'left'
      | 'right'
      | 'center'
      | 'topleft'
      | 'topright'
      | 'bottomleft'
      | 'bottomright'
      | string;
  }
```
should fix it.

### PR DESCRIPTION
**Pull request by MidnightDesign**

### CODE REVIEW

**Comment by Straightline** [comment]
Thanks for the PR. I will try to take a look at it over the weekend.

**Comment by DaddyWarbucks** [comment]
Thanks for the PR. I will try to take a look at it this weekend.

**Comment by DaddyWarbucks** [comment]
@bondz We never landed on getting me NPM creds in order to publish. 
This is ready to go and I have already bumped the version. Should just need an `npm publish`

**Comment by bondz** [comment]
@DaddyWarbucks I'll need your npm username.

**Comment by DaddyWarbucks** [comment]
Doh. Sorry. `daddywarbucks`

**Comment by bondz** [comment]
@DaddyWarbucks Thanks. Granted you access.

**Comment by DaddyWarbucks** [comment]
Thanks! @bondz 

@MidnightDesign Version 0.5.4 has been released to NPM. Thanks the the PR!

**Pull request merged**
